services:
  app:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    depends_on:
      - localstack
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
