FROM python:3.13-slim

# 作業ディレクトリを作成
WORKDIR /app

# 初回は poetry.lock が存在しないため COPY しない
COPY pyproject.toml ./

RUN pip install --upgrade pip \
 && pip install poetry \
 && poetry lock \
 && poetry install --no-root
# アプリケーションのコードをコピー
COPY . .

# デフォルトの実行コマンド
CMD ["/bin/bash"]
