FROM python:3.12-slim

# 作業ディレクトリを作成
WORKDIR /app

# Poetry設定とpoetry.lockをコピー
COPY pyproject.toml poetry.lock ./

RUN pip install --upgrade pip \
 && pip install poetry \
 && poetry install --no-root

# アプリケーションのコードをコピー
COPY . .

# デフォルトの実行コマンド（起動後にコンテナをすぐ終了させないため）
CMD ["/bin/bash"]